name: meson build
on: push
jobs:
  meson-build:
    runs-on: ubuntu-latest
    container: mesonbuild/eoan:latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: pip install meson ninja
      - run: meson build .
        env:
          CXX: g++
      - uses: actions/upload-aritfact@v2
        if: failure()
        with:
          name: meson_build_log
          path: build/meson-logs/build.txt  
